name: kruskal
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^1.0.3
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/uicons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/static/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/static/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/static/Inter-Black.ttf
          weight: 900  
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
          weight: 900  